gymMangmentSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
path('', views.home,name='home'),
path('pagedetail/<int:id>', views.page_detail, name='pagedetail'),
path('faq', views.faq_list, name='faq'),
path('enquiry', views.enquiry, name='enquiry'),
path('gallery', views.gallery, name='gallery'),
path('gallerydetail/<int:id>', views.gallery_detail, name='gallery_detail'),
path('pricing',views.pricing,name='pricing'),
path('accounts/signup',views.signup,name='signup'),
path('checkout/<int:plan_id>',views.checkout,name='checkout'),
path('checkout_session/<int:plan_id>',views.checkout_session,name='checkout_session'),
path('success',views.success,name='success'),
path('cancel',views.cancel,name='cancel'),
#start  user dashbard sections
path('user-dashboard',views.user_dashboard,name='user_dashboard'),
path('update-profile',views.update_profile,name='update_profile'),
# Trainer Login
path('trainerlogin',views.trainerlogin,name='trainerlogin'),
path('trainerlogout',views.trainerlogin,name='trainerlogout'),
path('trainer_profile',views.trainer_profile,name='trainer_profile'),
path('trainer_dashboard',views.trainer_dashboard,name='trainer_dashboard'),
path('trainer_subscribers',views.trainer_subscribers,name='trainer_subscribers'),
path('trainer_payments',views.trainer_payments,name='trainer_payments'),
path('trainer_changepassword',views.trainer_changepassword,name='trainer_changepassword'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

#banners
class Banners(models.Model):
	img=models.ImageField(upload_to="banners/")
	alt_text=models.CharField(max_length=150)

	class Meta:
		verbose_name_plural='Banners'

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Create your models here.
class Service(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="services/",null=True)


	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

#create page

class Page(models.Model):
	title=models.CharField(max_length=200)
	detail=models.TextField()


	def __str__(self):
		return self.title

#create FAQ

class Faq(models.Model):
	myquest=models.TextField()
	ans=models.TextField()


	def __str__(self):
		return self.myquest

#create Enquiry

class Enquiry(models.Model):
	full_name=models.CharField(max_length=200)
	email=models.CharField(max_length=150)
	detail=models.TextField()
	send_time=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.full_name

#ceate gallery model

class Gallery(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="gallery/",null=True)


	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

#create gallery image
class GalleryImage(models.Model):
	gallery=models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
	alt_text=models.CharField(max_length=150)
	img=models.ImageField(upload_to="gallery_imgs/",null=True)


	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Subscription Plans
class SubPlan(models.Model):
	title=models.CharField(max_length=150)
	price=models.IntegerField()
	max_member=models.IntegerField(null=True)
	highlight_status=models.BooleanField(default=False,null=True)
	validty_days=models.IntegerField(null=True)

	def __str__(self):
		return self.title

# Subscription Plans Features
class SubPlanFeature(models.Model):
	#subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	subplan=models.ManyToManyField(SubPlan)
	title=models.CharField(max_length=150)

	def __str__(self):
		return self.title


# create discount pakage

class PlanDiscount(models.Model):
	subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	total_months=models.IntegerField()
	total_discount=models.IntegerField()

	def __str__(self):
		return str(self.total_months)

# subscriber
class Subscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	mobile=models.CharField(max_length=20)
	address=models.TextField()
	img=models.ImageField(upload_to="subs/",null=True)

	def __str__(self):
		return str(self.user)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'


@receiver(post_save,sender=User)

def create_subscriber(sender,instance,created,**kwrags):
	if created:
		Subscriber.objects.create(user=instance)

#subscrition
class Subscription(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	plan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	price=models.CharField(max_length=50)
	reg_date=models.DateField(auto_now_add=True,null=True)

	def __str__(self):
		return str(self.plan)


# Trainer

class Trainer(models.Model):
	full_name=models.CharField(max_length=100)
	username=models.CharField(max_length=100,null=True)
	pwd=models.CharField(max_length=50,null=True)
	mobile=models.CharField(max_length=100)
	address=models.TextField()
	is_active=models.BooleanField(default=False)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers/",null=True)
	salary=models.IntegerField(default=0)

	facebook=models.CharField(max_length=200,null=True)
	pinterest=models.CharField(max_length=200,null=True)
	twitter=models.CharField(max_length=200,null=True)
	youtube=models.CharField(max_length=200,null=True)
	telegram=models.CharField(max_length=200,null=True)

	def __str__(self):
		return str(self.full_name)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# Assign Subscriber to Trainer
class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True)

	def __str__(self):
		return str(self.user)

# Trainer Achivements
class TrainerAchivement(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	title=models.CharField(max_length=100)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers_achivements/")

	def __str__(self):
		return str(self.title)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# TrainerSalary Model
class TrainerSalary(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	amt=models.IntegerField()
	amt_date=models.DateField()
	remarks=models.TextField(blank=True)

	class Meta:
		verbose_name_plural='Trainer Salary'

	def __str__(self):
		return str(self.trainer.full_name)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from . import models

class EnquiryForm(forms.ModelForm):
	class Meta:
		model=models.Enquiry
		fields=('full_name','email','detail')

class SignUp(UserCreationForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username','password1','password2')

class ProfileForm(UserChangeForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username')

class TrainerLoginForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('username','pwd')

class TrainerProfileForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('full_name','mobile','address','detail','img')

class TrainerChangePassword(forms.Form):
	old_password=forms.CharField(max_length=50,required=True)
	new_password=forms.CharField(max_length=50,required=True)

main/views.py
from django.shortcuts import render,redirect
from . import models
from . import forms
from django.db.models import Count
from django.template.loader import get_template

from datetime import timedelta
import stripe

# Home page
def home(request):
	banners=models.Banners.objects.all()
	g_imgs=models.GalleryImage.objects.all().order_by('id')[:9]
	services=models.Service.objects.all()[:3]
	return render(request, 'home.html',{'banners': banners,'services':services,'g_imgs':g_imgs})


# Page detail
def page_detail(request, id):
	page=models.Page.objects.get(id=id)

	return render(request, 'page.html',{'page':page})

# FAQ quest
def faq_list(request):
	faq=models.Faq.objects.all()[:3]
	return render(request, 'faq.html',{'faqs':faq})

# Enquiry
def enquiry(request):
	message=''
	if request.method=='POST':
		form=forms.EnquiryForm(request.POST)
		if form.is_valid():
			form.save()
			message='The Data has been saved'
	form=forms.EnquiryForm
	return render(request, 'enquiry.html',{'form':form,'message':message})

# show gallery

def gallery(request):
	gallery=models.Gallery.objects.all().order_by('-id')
	return render(request, 'gallery.html',{'gallerys':gallery})

# show gallery detail

def gallery_detail(request, id):
	gallery=models.Gallery.objects.get(id=id)
	gallery_imgs=models.GalleryImage.objects.filter(gallery=gallery).order_by('-id')
	return render(request, 'gallery_imgs.html',{'gallery_imgs':gallery_imgs})

# Subscription Plans
def pricing(request):
	pricing=models.SubPlan.objects.annotate(total_members=Count('subscription__id')).all().order_by('price')
	dfeatures=models.SubPlanFeature.objects.distinct('title');
	return render(request, 'pricing.html',{'plans':pricing,'dfeatures':dfeatures})

#Signup
def signup(request):
	message=None
	if request.method=='POST':
		form=forms.SignUp(request.POST)
		if form.is_valid():
			form.save()
			message='Thank you for register.'
	form=forms.SignUp
	return render(request, 'registration/signup.html',{'form':form,'message':message})

	# Subscription Plans
def checkout(request, plan_id):
	detailplan=models.SubPlan.objects.get(pk=plan_id)
	return render(request, 'checkout.html',{'plan':detailplan})


stripe.api_key='sk_test_51OxCMV03wdSJHu0rBuJT5DxQghVGoD4wiAI80iSOudZBs82qRwjNHw1ZbXQuXkITS5VDFgbHfMQWTIketRWYMS2P00k937Wiag'
def checkout_session(request,plan_id):
	plan=models.SubPlan.objects.get(pk=plan_id)
	session=stripe.checkout.Session.create(
		payment_method_types=['card'],
		line_items=[{
	      'price_data': {
	        'currency': 'usd',
	        'product_data': {
	          'name': plan.title,
	        },
	        'unit_amount': plan.price*100,
	      },
	      'quantity': 1,
	    }],
	    mode='payment',

	    success_url='http://127.0.0.1:8000/success?session_id={CHECKOUT_SESSION_ID}',
	    cancel_url='http://127.0.0.1:8000/cancel',
	    client_reference_id=plan_id
	)
	return redirect(session.url, code=303)

# Success
from django.core.mail import EmailMessage


def success(request):
	session = stripe.checkout.Session.retrieve(request.GET['session_id'])
	plan_id=session.client_reference_id
	plan=models.SubPlan.objects.get(pk=plan_id)
	user=request.user
	models.Subscription.objects.create(
		plan=plan,
		user=user,
		price=plan.price
	)
	subject='Order Email'
	html_content=get_template('orderemail.html').render({'title':plan.title})
	from_email='natasbest@gmail.com'

	msg = EmailMessage(subject, html_content, from_email, ['natasbest@gmail.com'])
	msg.content_subtype = "html"  # Main content is now text/html
	msg.send()

	return render(request, 'success.html')

# Cancel
def cancel(request):
	return render(request, 'cancel.html')

# User dashboard
def user_dashboard(request):
	current_plan=models.Subscription.objects.get(user=request.user)
	my_trainer=models.AssignSubscriber.objects.get(user=request.user)
	enddate=current_plan.reg_date+timedelta(days=current_plan.plan.validty_days)
	return render(request, 'user/dashboard.html',{
		'current_plan':current_plan,
		'my_trainer':my_trainer,
		'enddate':enddate
		})

def update_profile(request):
	message=None
	if request.method=='POST':
		form=forms.ProfileForm(request.POST,instance=request.user)
		if form.is_valid():
			form.save()
			message='The data has been saved'
	form=forms.ProfileForm(instance=request.user)
	return render(request, 'user/update-profile.html',{'form':form,'message':message})

# Create trainer login

def trainerlogin(request):
	msg=''
	if request.method=='POST':
		username=request.POST['username']
		pwd=request.POST['pwd']
		trainer=models.Trainer.objects.filter(username=username,pwd=pwd).count()
		if trainer > 0:
			trainer=models.Trainer.objects.filter(username=username,pwd=pwd).first()
			request.session['trainerLogin']=True
			request.session['trainerid']=trainer.id
			return redirect('/trainer_dashboard')
		else:
			msg='Invalid!!'
	form=forms.TrainerLoginForm
	return render(request, 'trainer/login.html',{'form':form,'msg':msg})

# Trainer Logout
def trainerlogout(request):
	del request.session['trainerLogin']
	return redirect('/trainerlogin')

# Trainer Dashboard
def trainer_dashboard(request):
	return render(request, 'trainer/dashboard.html')

# Trainer Profile
def trainer_profile(request):
	t_id=request.session['trainerid']
	trainer=models.Trainer.objects.get(pk=t_id)
	msg=None
	if request.method=='POST':
		form=forms.TrainerProfileForm(request.POST,request.FILES,instance=trainer)
		if form.is_valid():
			form.save()
			msg='Profile has been updated'
	form=forms.TrainerProfileForm(instance=trainer)
	return render(request, 'trainer/profile.html',{'form':form,'msg':msg})
# Trainer Subscribers
def trainer_subscribers(request):
	trainer=models.Trainer.objects.get(pk=request.session['trainerid'])
	trainer_subs=models.AssignSubscriber.objects.filter(trainer=trainer).order_by('-id')
	return render(request, 'trainer/trainer_subscribers.html',{'trainer_subs':trainer_subs})

	# Trainer Payments
def trainer_payments(request):
	trainer=models.Trainer.objects.get(pk=request.session['trainerid'])
	trainer_pays=models.TrainerSalary.objects.filter(trainer=trainer).order_by('-id')
	return render(request, 'trainer/trainer_payments.html',{'trainer_pays':trainer_pays})

# Trainer Change Password
def trainer_changepassword(request):
	msg=None
	if request.method=='POST':
		new_password=request.POST['new_password']
		updateRes=models.Trainer.objects.filter(pk=request.session['trainerid']).update(pwd=new_password)
		if updateRes:
			del request.session['trainerLogin']
			return redirect('/trainerlogin')
		else:
			msg='Something is wrong!!'
	form=forms.TrainerChangePassword
	return render(request, 'trainer/trainer_changepassword.html',{'form':form})

# Trainer Change Password
def trainer_changepassword(request):
	msg=None
	if request.method=='POST':
		new_password=request.POST['new_password']
		updateRes=models.Trainer.objects.filter(pk=request.session['trainerid']).update(pwd=new_password)
		if updateRes:
			del request.session['trainerLogin']
			return redirect('/trainerlogin')
		else:
			msg='Something is wrong!!'
	form=forms.TrainerChangePassword
	return render(request, 'trainer/trainer_changepassword.html',{'form':form})

main/templates/user/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4" class="left">

			<div class="row">

				<div class="col-3">
				{% include 'user/left-sidebar.html' %}
				</div>
			</div class="col-9">

			<h3 class="mb-4 border-bottom pb-1">Dashboard</h3>
			<div class="row">
				<div class="col-md-6">
					<div class="card">
						<h5 class="card-header"> Current package</h5>
						<div class="card-body">
							<p class="card-text">{{current_plan.plan}}</p>
							<p>price:{{current_plan.price}}</p>
							<p>Purchase Date:{{current_plan.reg_date}}</p>
							<p>Expired Date:{{enddate}}</p>
						</div>
					</div>
				</div class="col-md-6">
				<div class="col-md-4">
					<div class="card">
						<h5 class="card-header"> Assigned Trainer</h5>
						<img src="{{my_trainer.trainer.img.url}}" class="card-img-top" alt="{{my_trainer.trainer}}">
						<div class="card-body">
									<h6 class="card-text">{{my_trainer.trainer}}</h6>
							<div class="card-footer">
								<a href="{{my_trainer.trainer.facebook}}" title="Facebook"><i class="bi bi-facebook"></i></a>
									<a href="{{my_trainer.trainer.twitter}}" title="Twitter"><i class="bi bi-twitter"></i></a>
									<a href="{{my_trainer.trainer.telegram}}" title="telegram"><i class="bi bi-telegram"></i></a>
									<a href="{{my_trainer.trainer.youtube}}"><i class="bi bi-youtube" title="YouTube"></i></a>
									<a href="{{my_trainer.trainer.pinterest}}"><i class="bi bi-pinterest" title="pinterest"></i></a>
									<button data-bs-toggle="modal" data-bs-target="#AchivementModal" title="Achivement" class="float-end btn btn-sm btn-success"><i class="bi bi-trophy-fill"></i></button>
				<!-- Modal -->
<div class="modal fade" id="AchivementModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title fs-5" id="exampleModalLabel">{{my_trainer.trainer.full_name}}  Achivements</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      	     <table class="table table-hover">
        	<thead>
        		<tr>
        			<th>Title</th>
        			<th>Image</th>
        			<th>Detail</th>
        		</tr>
        	</thead>
        	<tbody>
        		{% for achive in  my_trainer.trainer.trainerachivement_set.all %}
        		<tr>
	        		<td>{{achive.title}}</td>
	        		<td><img src="{{achive.img.url}}" width="80" /></td>
	        		<td>{{achive.detail}}</td>
	        	</tr>
	        	{% endfor %}
        	</tbody>
        </table>

    </div>
  </div>
</div>


							</div>


						</div>
					</div>
				</div>
			</div>

		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/user/left-sidebar.html
<div class="list-group">
	<a href="{% url 'user_dashboard' %}" class="list-group-item {% if request.path == '/user-dashboard' %} active {% endif %}">Dashboard</a>
	<a href="{% url 'update_profile' %}" class="list-group-item {% if request.path == '/update-profile' %} active {% endif %}">Profile</a>
	<a href="{% url 'password_change' %}" class="list-group-item {% if request.path == '/password-change' %} active {% endif %}">Change Password</a>
</div>

main/templates/user/update-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-2">
			<h5 class="mb-6 border-bottom pb-2">Dashboard</h5>
			<div class="row">
				<div class="col-3">
					{% include 'user/left-sidebar.html' %}
			</div>
			</div class="col-9">
			<h3 class="mb-4 border-bottom pb-1">Update Profile</h3>
			<form method="post" action="">
				{% if msg %}
					<p class="text-success">{{message}}</p>
					{% endif %}
						<table class="table table-bordered">
							{% csrf_token %}
							{{form.as_table}}
							<tr>
								<td colspan="4">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>

		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}