gymMangmentSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
path('', views.home,name='home'),
path('pagedetail/<int:id>', views.page_detail, name='pagedetail'),
path('faq', views.faq_list, name='faq'),
path('enquiry', views.enquiry, name='enquiry'),
path('gallery', views.gallery, name='gallery'),
path('gallerydetail/<int:id>', views.gallery_detail, name='gallery_detail'),
path('pricing',views.pricing,name='pricing'),
path('accounts/signup',views.signup,name='signup'),
path('checkout/<int:plan_id>',views.checkout,name='checkout'),
path('checkout_session/<int:plan_id>',views.checkout_session,name='checkout_session'),
path('success',views.success,name='success'),
path('cancel',views.cancel,name='cancel'),
#start  user dashbard sections
path('user-dashboard',views.user_dashboard,name='user_dashboard'),
path('update-profile',views.update_profile,name='update_profile'),
# Trainer Login
path('trainerlogin',views.trainerlogin,name='trainerlogin'),
path('trainerlogout',views.trainerlogin,name='trainerlogout'),
path('trainer_profile',views.trainer_profile,name='trainer_profile'),
path('trainer_dashboard',views.trainer_dashboard,name='trainer_dashboard'),
path('trainer_subscribers',views.trainer_subscribers,name='trainer_subscribers'),
path('trainer_payments',views.trainer_payments,name='trainer_payments'),
path('trainer_changepassword',views.trainer_changepassword,name='trainer_changepassword'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

#banners
class Banners(models.Model):
	img=models.ImageField(upload_to="banners/")
	alt_text=models.CharField(max_length=150)

	class Meta:
		verbose_name_plural='Banners'

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Create your models here.
class Service(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="services/",null=True)


	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

#create page

class Page(models.Model):
	title=models.CharField(max_length=200)
	detail=models.TextField()


	def __str__(self):
		return self.title

#create FAQ

class Faq(models.Model):
	myquest=models.TextField()
	ans=models.TextField()


	def __str__(self):
		return self.myquest

#create Enquiry

class Enquiry(models.Model):
	full_name=models.CharField(max_length=200)
	email=models.CharField(max_length=150)
	detail=models.TextField()
	send_time=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.full_name

#ceate gallery model

class Gallery(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="gallery/",null=True)


	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

#create gallery image
class GalleryImage(models.Model):
	gallery=models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
	alt_text=models.CharField(max_length=150)
	img=models.ImageField(upload_to="gallery_imgs/",null=True)


	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Subscription Plans
class SubPlan(models.Model):
	title=models.CharField(max_length=150)
	price=models.IntegerField()
	max_member=models.IntegerField(null=True)
	highlight_status=models.BooleanField(default=False,null=True)
	validty_days=models.IntegerField(null=True)

	def __str__(self):
		return self.title

# Subscription Plans Features
class SubPlanFeature(models.Model):
	#subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	subplan=models.ManyToManyField(SubPlan)
	title=models.CharField(max_length=150)

	def __str__(self):
		return self.title


# create discount pakage

class PlanDiscount(models.Model):
	subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	total_months=models.IntegerField()
	total_discount=models.IntegerField()

	def __str__(self):
		return str(self.total_months)

# subscriber
class Subscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	mobile=models.CharField(max_length=20)
	address=models.TextField()
	img=models.ImageField(upload_to="subs/",null=True)

	def __str__(self):
		return str(self.user)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'


@receiver(post_save,sender=User)

def create_subscriber(sender,instance,created,**kwrags):
	if created:
		Subscriber.objects.create(user=instance)

#subscrition
class Subscription(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	plan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	price=models.CharField(max_length=50)
	reg_date=models.DateField(auto_now_add=True,null=True)

	def __str__(self):
		return str(self.plan)


# Trainer

class Trainer(models.Model):
	full_name=models.CharField(max_length=100)
	username=models.CharField(max_length=100,null=True)
	pwd=models.CharField(max_length=50,null=True)
	mobile=models.CharField(max_length=100)
	address=models.TextField()
	is_active=models.BooleanField(default=False)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers/",null=True)
	salary=models.IntegerField(default=0)

	facebook=models.CharField(max_length=200,null=True)
	pinterest=models.CharField(max_length=200,null=True)
	twitter=models.CharField(max_length=200,null=True)
	youtube=models.CharField(max_length=200,null=True)
	telegram=models.CharField(max_length=200,null=True)

	def __str__(self):
		return str(self.full_name)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# Assign Subscriber to Trainer
class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True)

	def __str__(self):
		return str(self.user)

# Trainer Achivements
class TrainerAchivement(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	title=models.CharField(max_length=100)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers_achivements/")

	def __str__(self):
		return str(self.title)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# TrainerSalary Model
class TrainerSalary(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	amt=models.IntegerField()
	amt_date=models.DateField()
	remarks=models.TextField(blank=True)

	class Meta:
		verbose_name_plural='Trainer Salary'

	def __str__(self):
		return str(self.trainer.full_name)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from . import models

class EnquiryForm(forms.ModelForm):
	class Meta:
		model=models.Enquiry
		fields=('full_name','email','detail')

class SignUp(UserCreationForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username','password1','password2')

class ProfileForm(UserChangeForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username')

class TrainerLoginForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('username','pwd')

class TrainerProfileForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('full_name','mobile','address','detail','img')

class TrainerChangePassword(forms.Form):
	old_password=forms.CharField(max_length=50,required=True)
	new_password=forms.CharField(max_length=50,required=True)

main/views.py
from django.shortcuts import render,redirect
from . import models
from . import forms
from django.db.models import Count
from django.template.loader import get_template

from datetime import timedelta
import stripe

# Home page
def home(request):
	banners=models.Banners.objects.all()
	g_imgs=models.GalleryImage.objects.all().order_by('id')[:9]
	services=models.Service.objects.all()[:3]
	return render(request, 'home.html',{'banners': banners,'services':services,'g_imgs':g_imgs})


# Page detail
def page_detail(request, id):
	page=models.Page.objects.get(id=id)

	return render(request, 'page.html',{'page':page})

# FAQ quest
def faq_list(request):
	faq=models.Faq.objects.all()[:3]
	return render(request, 'faq.html',{'faqs':faq})

# Enquiry
def enquiry(request):
	message=''
	if request.method=='POST':
		form=forms.EnquiryForm(request.POST)
		if form.is_valid():
			form.save()
			message='The Data has been saved'
	form=forms.EnquiryForm
	return render(request, 'enquiry.html',{'form':form,'message':message})

# show gallery

def gallery(request):
	gallery=models.Gallery.objects.all().order_by('-id')
	return render(request, 'gallery.html',{'gallerys':gallery})

# show gallery detail

def gallery_detail(request, id):
	gallery=models.Gallery.objects.get(id=id)
	gallery_imgs=models.GalleryImage.objects.filter(gallery=gallery).order_by('-id')
	return render(request, 'gallery_imgs.html',{'gallery_imgs':gallery_imgs})

# Subscription Plans
def pricing(request):
	pricing=models.SubPlan.objects.annotate(total_members=Count('subscription__id')).all().order_by('price')
	dfeatures=models.SubPlanFeature.objects.distinct('title');
	return render(request, 'pricing.html',{'plans':pricing,'dfeatures':dfeatures})

#Signup
def signup(request):
	message=None
	if request.method=='POST':
		form=forms.SignUp(request.POST)
		if form.is_valid():
			form.save()
			message='Thank you for register.'
	form=forms.SignUp
	return render(request, 'registration/signup.html',{'form':form,'message':message})

	# Subscription Plans
def checkout(request, plan_id):
	detailplan=models.SubPlan.objects.get(pk=plan_id)
	return render(request, 'checkout.html',{'plan':detailplan})


stripe.api_key='sk_test_51OxCMV03wdSJHu0rBuJT5DxQghVGoD4wiAI80iSOudZBs82qRwjNHw1ZbXQuXkITS5VDFgbHfMQWTIketRWYMS2P00k937Wiag'
def checkout_session(request,plan_id):
	plan=models.SubPlan.objects.get(pk=plan_id)
	session=stripe.checkout.Session.create(
		payment_method_types=['card'],
		line_items=[{
	      'price_data': {
	        'currency': 'usd',
	        'product_data': {
	          'name': plan.title,
	        },
	        'unit_amount': plan.price*100,
	      },
	      'quantity': 1,
	    }],
	    mode='payment',

	    success_url='http://127.0.0.1:8000/success?session_id={CHECKOUT_SESSION_ID}',
	    cancel_url='http://127.0.0.1:8000/cancel',
	    client_reference_id=plan_id
	)
	return redirect(session.url, code=303)

# Success
from django.core.mail import EmailMessage


def success(request):
	session = stripe.checkout.Session.retrieve(request.GET['session_id'])
	plan_id=session.client_reference_id
	plan=models.SubPlan.objects.get(pk=plan_id)
	user=request.user
	models.Subscription.objects.create(
		plan=plan,
		user=user,
		price=plan.price
	)
	subject='Order Email'
	html_content=get_template('orderemail.html').render({'title':plan.title})
	from_email='natasbest@gmail.com'

	msg = EmailMessage(subject, html_content, from_email, ['natasbest@gmail.com'])
	msg.content_subtype = "html"  # Main content is now text/html
	msg.send()

	return render(request, 'success.html')

# Cancel
def cancel(request):
	return render(request, 'cancel.html')

# User dashboard
def user_dashboard(request):
	current_plan=models.Subscription.objects.get(user=request.user)
	my_trainer=models.AssignSubscriber.objects.get(user=request.user)
	enddate=current_plan.reg_date+timedelta(days=current_plan.plan.validty_days)
	return render(request, 'user/dashboard.html',{
		'current_plan':current_plan,
		'my_trainer':my_trainer,
		'enddate':enddate
		})

def update_profile(request):
	message=None
	if request.method=='POST':
		form=forms.ProfileForm(request.POST,instance=request.user)
		if form.is_valid():
			form.save()
			message='The data has been saved'
	form=forms.ProfileForm(instance=request.user)
	return render(request, 'user/update-profile.html',{'form':form,'message':message})

# Create trainer login

def trainerlogin(request):
	msg=''
	if request.method=='POST':
		username=request.POST['username']
		pwd=request.POST['pwd']
		trainer=models.Trainer.objects.filter(username=username,pwd=pwd).count()
		if trainer > 0:
			trainer=models.Trainer.objects.filter(username=username,pwd=pwd).first()
			request.session['trainerLogin']=True
			request.session['trainerid']=trainer.id
			return redirect('/trainer_dashboard')
		else:
			msg='Invalid!!'
	form=forms.TrainerLoginForm
	return render(request, 'trainer/login.html',{'form':form,'msg':msg})

# Trainer Logout
def trainerlogout(request):
	del request.session['trainerLogin']
	return redirect('/trainerlogin')

# Trainer Dashboard
def trainer_dashboard(request):
	return render(request, 'trainer/dashboard.html')

# Trainer Profile
def trainer_profile(request):
	t_id=request.session['trainerid']
	trainer=models.Trainer.objects.get(pk=t_id)
	msg=None
	if request.method=='POST':
		form=forms.TrainerProfileForm(request.POST,request.FILES,instance=trainer)
		if form.is_valid():
			form.save()
			msg='Profile has been updated'
	form=forms.TrainerProfileForm(instance=trainer)
	return render(request, 'trainer/profile.html',{'form':form,'msg':msg})
# Trainer Subscribers
def trainer_subscribers(request):
	trainer=models.Trainer.objects.get(pk=request.session['trainerid'])
	trainer_subs=models.AssignSubscriber.objects.filter(trainer=trainer).order_by('-id')
	return render(request, 'trainer/trainer_subscribers.html',{'trainer_subs':trainer_subs})

	# Trainer Payments
def trainer_payments(request):
	trainer=models.Trainer.objects.get(pk=request.session['trainerid'])
	trainer_pays=models.TrainerSalary.objects.filter(trainer=trainer).order_by('-id')
	return render(request, 'trainer/trainer_payments.html',{'trainer_pays':trainer_pays})

# Trainer Change Password
def trainer_changepassword(request):
	msg=None
	if request.method=='POST':
		new_password=request.POST['new_password']
		updateRes=models.Trainer.objects.filter(pk=request.session['trainerid']).update(pwd=new_password)
		if updateRes:
			del request.session['trainerLogin']
			return redirect('/trainerlogin')
		else:
			msg='Something is wrong!!'
	form=forms.TrainerChangePassword
	return render(request, 'trainer/trainer_changepassword.html',{'form':form})

# Trainer Change Password
def trainer_changepassword(request):
	msg=None
	if request.method=='POST':
		new_password=request.POST['new_password']
		updateRes=models.Trainer.objects.filter(pk=request.session['trainerid']).update(pwd=new_password)
		if updateRes:
			del request.session['trainerLogin']
			return redirect('/trainerlogin')
		else:
			msg='Something is wrong!!'
	form=forms.TrainerChangePassword
	return render(request, 'trainer/trainer_changepassword.html',{'form':form})

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Bootstrap Icons -->
   <link href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet" />
    <!-- jquery -->
    <script type="text/javascript" src="{% static 'jquery-3.7.1.min.js' %}"></script>
    <title>Home - Natoli GYM</title>
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
	  <div class="container">
	    <a class="navbar-brand" href="{% url 'home' %}">Natoli GYM</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	      <ul class="navbar-nav ms-auto">
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'gallery' %}">Gallery</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link btn btn-sm btn-dark text-white" href="{% url 'enquiry' %}">Enquiry</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	            My Account
	          </a>
	          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
	            	{% if not request.user.is_authenticated %}
	            	{% if request.session.trainerLogin %}
	            	<li><a class="dropdown-item" href="{% url 'trainer_dashboard' %}"> Dashboard</a></li>
	            	 <li><a class="dropdown-item" href="{% url 'trainerlogin' %}">Trainer Logout</a></li>
	            	 {% else %}
	            	 <li><a class="dropdown-item" href="{% url 'trainerlogin' %}">Trainer Login</a></li>
	            	 <li><a class="dropdown-item" href="{% url 'signup' %}">Register</a></li>
		            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
		            {% endif %}
		            {% else %}
	            <li><a class="dropdown-item" href="{% url 'user_dashboard' %}">Dashboard</a></li>
	            <li><a class="dropdown-item" href="{% url 'trainer_dashboard' %}"> Dashboard</a></li>
	            <li><a class="dropdown-item" href="{% url 'update_profile' %}">Profile</a></li>
	            <li><a class="dropdown-item" href="{% url 'login' %}">Logout</a></li>
	            {% endif %}
	          </ul>
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
    <!-- Header End -->

      <!-- start our footer-->

      {% block content %}

      {% endblock %}


        <footer class="container py-5">
	    <p class="float-end"><a href="#">Back to top</a></p>
	  <p>© 2024 Natoli GYM, Inc. ·
        <a href="{% url 'pagedetail' 2 %}">Privacy</a> ·
        <a href="{% url 'pagedetail' 1 %}">Terms</a> .
        <a href="{% url 'faq' %}">FAQ</a> .
        <a href="{% url 'pagedetail' 4%}">Contact Us</a> .
      </p>
	  </footer>

    <!-- Bootstrap Bundle -->
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>

  </body>
</html>

main/templates/cancel.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h3>Sorry!! Please try again</h3>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
				<table class="table table-bordered">
					<thead class="table-warning">
						<tr>
							<th>Plan</th>
							<th>detail plan</th>
							<th>Payment For</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<table class="table-bordered table">
									<tr>
										<th>Name</th>
										<td>{{plan.title}}</td>
									</tr>
									<tr>
										<th>Price</th>
										<td>{{plan.price}}</td>
									</tr>
									<tr>
										<th>Max Member</th>
										<td>30</td>
									</tr>
									<tr>
										<th>Already Registered</th>
										<td>15</td>
									</tr>
									<tr>
										<th>Balance Seats</th>
										<td>15</td>
									</tr>
								</table>
							</td>
							<td>
								<ul class="list-unstyled">
					              {% for feature in plan.subplanfeature_set.all %}
						            <li>{{feature.title}}</li>
				            	{% endfor %}
					            </ul>
							</td>
							<td>
								<table class="table table-bordered">
									{% for discount in plan.plandiscount_set.all %}

									<tr>
										<td><input data-planprice="{{plan.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity{{discount.id}}" name="validity" class="select-validity" value="{{discount.total_months}}" /></td>
										<th><label for="validity{{discount.id}}">{{discount.total_months}}Month</label></th>
										<td>{{discount.total_discount}} %</td>
									</tr>

				            	{% endfor %}

								</table>
							</td>
						</tr>
					</tbody>
					<tfoot class="table-info">
						<tr>
							<td></td>
							<th>Total Amount</th>
							<td><b>$<span class="totalAmount">{{plan.price}}</span></b></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td>
								<form method="post" action="{% url 'checkout_session' plan.id %}">
									{% csrf_token %}
									<input type="submit" value="Proceed to Payment" class="btn btn-primary" />
								</form>

						</tr>
					</tfoot>
				</table>
		</section>
		<!-- End -->
    </main>

<script type="text/javascript">
	$(document).ready(function(){
		$(".select-validity").on('click',function(){
			var _planPrice=$(this).attr('data-planprice');
			var _planValid=$(this).val();
			var _planDisc=$(this).attr('data-discount');
			var _totalPrice=_planPrice*_planValid;
			if(_planDisc>0){
				var _calDisc=_totalPrice*_planDisc/100;
				_calDisc=_totalPrice-_calDisc;
			}else{
				_calDisc=_planPrice;
			}
			$(".totalAmount").text(_calDisc);
		});
	});
</script>

    <!-- End -->
{% endblock %}

main/templates/enquiry.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
			<div class="row">
				<div class="col-md-6">
					<img src="{% static 'imgs/120462.jpg' %}" class="img-fluid" />
				</div>
				<div class="col-md-6">
					{% if message %}
					<p class="text-success">{{message}}</p>
					{% endif %}
					<form method="post" action="{% url 'enquiry' %}">
						{% csrf_token %}
						<table class="table table-bordered">
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/faq.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
			<div class="accordion" id="accordionExample">
				{% for faq in faqs %}

				  <div class="accordion-item">
				    <h2 class="accordion-header" id="headingOne">
				      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
				        {{faq.myquest}}
				      </button>
				    </h2>
				    <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
				      <div class="accordion-body">
				        {{faq.ans}}
				      </div>
				    </div>
				  </div>
				  {% endfor %}

			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/pricing.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
<section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plan</h1>
<main>
  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for plan in plans %}

    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
        {% if plan.highlight_status %}
        <div class="card-header py-3 text-white bg-primary border-primary">
          {% else %}
        <div class="card-header py-3">
          {% endif %}
          <h4 class="my-0 fw-normal">{{plan.title}}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">${{plan.price}}
            <small class="text-muted fw-light">/{{plan.validty_days}} Days</small>
          </h1>
          <p class="text-success">Member Capacity {{plan.max_member|sub:plan.total_members}}</p>
          <ul class="list-unstyled mt-3 mb-4">
            {% for feature in plan.subplanfeature_set.all %}
            <li>{{feature.title}}</li>
            {% endfor %}
          </ul>
          {% if request.user.is_authenticated %}
          <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% else %}
          <a href="{% url 'login' %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <h2 class="display-6 text-center mb-4">Compare plans</h2>
  <div class="table-responsive">
    <table class="table text-center">
      <thead>
        <tr>
          <th style="width: 34%;"></th>
          {% for plan in plans %}
          <th style="width: 22%;">{{plan.title}}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for feature in dfeatures %}
        <tr>
          <th scope="row" class="text-start">{{feature.title}}</th>
          {% for plan in plans %}
          <td>
            {% if plan in feature.subplan.all %}
            <i class="bi bi-check-lg"></i>
            {% else %}
            <i class="bi bi-x-lg text-danger"></i>
            {% endif %}
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
</section>
{% endblock %}